import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import categories from './src/categories';

const sidebars: SidebarsConfig = categories.reduce((acc, { id, label }) => {
  const sidebar = [
    {
      type: 'category',
      label,
      link: {
        type: 'doc',
        id,
      },
      items: [
        {
          type: 'autogenerated',
          dirName: id,
        },
      ],
    },
  ];

  acc[id] = sidebar;
  return acc;
}, {} as SidebarsConfig);

export default sidebars;
