import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import categories from './src/categories';

const sidebars: SidebarsConfig = Object.fromEntries(
  categories.map(({ id, label }) => [
    id,
    [
      {
        type: 'category',
        label,
        link: {
          type: 'doc',
          id,
        },
        items: [
          {
            type: 'autogenerated',
            dirName: id,
          },
        ],
      },
    ],
  ])
);

export default sidebars;
